# Generated by Django 5.0.2 on 2024-03-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_alter_fotografia_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[(' ', ' '), ('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela'), ('PLANETA', 'Planeta'), ('GALÁXIA', 'Galáxia'), ('BURACO NEGRO', 'BURACO NEGRO'), ('SUPERMASSIVO BURACO NEGRO', 'Supermassivo Buraco Negro')], max_length=50),
        ),
    ]
